dnd-side-project/dnd-11th-10-backend

.github/workflows/backend-pr-test.yml, .github/workflows/backend-publish.yml
- closed #8  
develop 브랜치 최신화
해당 PR이 Approve 되면 바로 main 브랜치에도 동일한 브랜치 최신화 작업을 진행할 예정입니다
=> Synchronize develop Branch

Dockerfile
- closes #14 
main 브랜치 최신화
x
도커 관련 CI/CD 작업 때문에 빠르게 main 으로 올리겠습니다
=> Synchronize main Branch

src/main/java/com/dnd/spaced/domain/learning/LeaningController.java, src/main/java/com/dnd/spaced/domain/learning/dto/response/TestExplanationResponse.java, src/main/java/com/dnd/spaced/domain/learning/dto/response/TestProblemResponse.java
- closed #40 
- 기획 변경으로 인한 용어 테스트 응답 포맷, 목 데이터 변경
- 용어 이름을 한글(영어) 방식으로 변경
- 용어 테스트 문제에서 용어를 언급할 때 용어 이름과 같은 방식으로 문제를 명시
- 용어 이름, 용어 테스트 문제 포맷 변경으로 인해 필요 없어진 응답 포맷 삭제
x
[슬랙 메시지 링크](https://dnd-ayn8252.slack.com/archives/C07AELHJYV9/p1723121433381909?thread_ts=1723087996.460899&cid=C07AELHJYV9) 기준으로 변경한 결과입니다
=> Change Word Test Response

src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultiplePopularCommentInfoDto.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultiplePopularCommentInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/application/WordService.java, src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java, src/main/java/com/dnd/spaced/domain/word/application/dto/request/SearchWordConditionInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/request/WordConditionInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/WordSearchInfoDto.java, src/main/java/com/dnd/spaced/domain/word/domain/Pronunciation.java, src/main/java/com/dnd/spaced/domain/word/domain/Word.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/WordRepositoryMapper.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/request/SearchWordConditionDto.java, src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/WordSearchRequest.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleSearchWordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/WordSearchResponse.java, src/main/java/com/dnd/spaced/global/config/AppConfig.java, src/main/java/com/dnd/spaced/global/config/SecurityConfig.java, src/main/java/com/dnd/spaced/global/resolver/word/SearchWordSortCondition.java, src/main/java/com/dnd/spaced/global/resolver/word/SearchWordSortConditionArgumentResolver.java
- closed #49 
- 버그
- 용어 목록 조회 시 카테고리를 입력하지 않으면 예외가 발생하던 문제 
- 용어 검색 시 반드시 인가가 필요하던 문제 
- 용어 검색 시 반드시 page, size를 입력해야 했던 문제 
- 용어 검색 시 한 페이지의 크기가 20이던 문제 
- 용어와 관련된 모든 기능이 인가가 필요하던 문제 
- 기획 변경으로 인한 수정 
- 용어 목록 조회, 용어 검색 시 북마크 여부를 응답 값에서 삭제 
- 용어 한글 발음 제거  
x
x
=> Change Word API

src/main/java/com/dnd/spaced/domain/comment/application/CommentService.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/CommentServiceMapper.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/request/ReadCommentAllByLikedDto.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/request/ReadCommentAllByWrittenDto.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/response/LikedCommentDto.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/response/WrittenCommentDto.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/CommentRepository.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/QuerydslCommentRepository.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/dto/request/FindCommentAllByLikedConditionDto.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/dto/request/FindCommentAllByWrittenConditionDto.java, src/main/java/com/dnd/spaced/domain/comment/presentation/CommentController.java, src/main/java/com/dnd/spaced/domain/comment/presentation/SwaggerCommentController.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/CommentControllerMapper.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/request/CommentConditionRequest.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/request/ReadLikedCommentRequest.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/request/ReadWrittenCommentRequest.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/LikedCommentResponse.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/WrittenCommentResponse.java, src/main/java/com/dnd/spaced/global/config/AppConfig.java, src/main/java/com/dnd/spaced/global/resolver/comment/LikedCommentSortCondition.java, src/main/java/com/dnd/spaced/global/resolver/comment/LikedCommentSortConditionArgumentResolver.java, src/main/java/com/dnd/spaced/global/resolver/comment/WrittenCommentSortCondition.java, src/main/java/com/dnd/spaced/global/resolver/comment/WrittenCommentSortConditionArgumentResolver.java
- closed #53 
- 좋아요한 댓글 목록 조회 
- 내가 작성한 댓글 목록 조회
- 추가한 기능에 대한 swagger 문서 추가 
x
x
=> Add Comment Function Related To Account

src/main/java/com/dnd/spaced/domain/account/domain/Company.java, src/main/java/com/dnd/spaced/domain/account/domain/JobGroup.java, src/main/java/com/dnd/spaced/domain/auth/presentation/AuthController.java, src/main/java/com/dnd/spaced/domain/auth/presentation/SwaggerAuthController.java, src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java, src/main/java/com/dnd/spaced/domain/auth/presentation/dto/response/TokenResponse.java, src/main/java/com/dnd/spaced/global/config/DocsConfig.java, src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
- closed #59 
인증/인가 관련 API 문서 추가
x
Spring Security OAuth2 Client을 사용해 로그인 처리를 진행하기 때문에 로그인 관련된 별도 메서드가 없습니다
그래서 DocsConfig에 수동으로 로그인 처리를 등록해줬습니다
=> Add Auth API Documentation

src/main/java/com/dnd/spaced/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/SwaggerBookmarkController.java, src/main/java/com/dnd/spaced/global/config/AppConfig.java, src/main/java/com/dnd/spaced/global/resolver/bookmark/BookmarkSortCondition.java, src/main/java/com/dnd/spaced/global/resolver/bookmark/BookmarkSortConditionArgumentResolver.java
- closed #63 
북마크 관련 API 문서 추가
x
x
=> Add Bookmark API Documentation

src/main/java/com/dnd/spaced/domain/account/domain/JobGroup.java, src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java
- closed #67 
- 회원 직군에 기타 요소 추가
- 회원가입 시 사용하는 API 문서 업데이트
x
x
=> Add Account JobGroup Element

src/main/java/com/dnd/spaced/domain/admin/application/AdminService.java, src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java, src/main/java/com/dnd/spaced/domain/admin/application/dto/request/AdminWordRequestDto.java, src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java, src/main/java/com/dnd/spaced/domain/word/domain/Pronunciation.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordCrudRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java, src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
- closes #74 
용어 관련 어드민 기능 구현
x
x
=> Add Admin Function Related To Word

src/main/java/com/dnd/spaced/domain/quiz/presentation/QuizController.java, src/main/java/com/dnd/spaced/domain/quiz/presentation/SwaggerQuizController.java, src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/request/QuizRequest.java, src/main/java/com/dnd/spaced/domain/quiz/presentation/dto/response/QuizResponse.java, src/main/java/com/dnd/spaced/global/exception/ExceptionTranslator.java
- closes #66 
퀴즈 API 문서 추가
x
x
=> Add Word Quiz Documentation

src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultiplePopularCommentInfoDto.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/QuerydslCommentRepository.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/dto/response/PopularCommentInfoDto.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/CommentControllerMapper.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultiplePopularCommentInfoResponse.java
- closed #80 
반응이 뜨거운 댓글 응답 포맷 변경
x
x
=> Change Popular Comment Response Format

Dockerfile
- closes #86 
- `-Dspring.profiles.active=prod` 옵션 추가
- jar 파일 이름 명시
x
x
=> Refactor Docker File

src/main/java/com/dnd/spaced/domain/word/application/WordService.java, src/main/java/com/dnd/spaced/domain/word/application/dto/WordServiceMapper.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/InputWordCandidateDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/WordSearchInfoDto.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/WordRepositoryMapper.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordCandidateDto.java, src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/InputWordCandidateResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleSearchWordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/MultipleWordInfoResponse.java
- closed #88 
- 용어 사전 목록 조회, 용어 검색 시 댓글 수 응답 포맷에 추가
- 용어 사전 목록 조회, 용어 검색 시 발음 관련 정보 응답 포맷에서 삭제
- 용어 검색어 후보군 조회 시 카테고리 응답에 포함
x
x
=> Change Word Response Format

src/main/java/com/dnd/spaced/domain/admin/presentation/AdminController.java, src/main/java/com/dnd/spaced/domain/admin/presentation/SwaggerAdminController.java, src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
- closes #94
어드민 요청 권한 인증 처리 로직 추가
x
x
=> Add Admin Permissions Handling

src/main/resources/application.yml
- closes #100 
active 세팅 이후 502 에러로 인해 제거
x
x
=> remove active setting

src/main/java/com/dnd/spaced/SpacedApplication.java
=> remove configuration properties scan

src/main/resources/application-local.yml
- closes #100 
오류 로그에 따라 닉네임 포맷 수정
x
x
=> fix nickname format

src/main/java/com/dnd/spaced/global/config/DocsConfig.java
- closes #105 
swagger 문서 title 수정
x
x
=> Fix Swagger Title

src/main/java/com/dnd/spaced/SpacedApplication.java
- closes #107 
`@ConfigurationPropertiesScan` 어노테이션 재설정
x
x
=> hotfix :: add properties scan

src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java, src/main/java/com/dnd/spaced/domain/admin/application/dto/request/AdminWordRequestDto.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java, src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/response/BookmarkWordDto.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/ListWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/domain/Word.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordInfoWithBookmarkDto.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
- closes #113 
- 디자인 수정에 따라 용어 예문 타입을 리스트로 수정
x
x
=> Change Examples Type To List

src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java, src/main/java/com/dnd/spaced/domain/admin/application/dto/request/AdminWordRequestDto.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java, src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/response/BookmarkWordDto.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/DetailWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/ListWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/application/dto/response/MultipleWordInfoDto.java, src/main/java/com/dnd/spaced/domain/word/domain/Word.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/dto/response/WordInfoWithBookmarkDto.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/DetailWordInfoResponse.java
- closes #119 
Reverts dnd-side-project/dnd-11th-10-backend#115
변경된 기획에 따라 example 타입 String 으로 롤백
x
x
=> Revert "Change Examples Type To List"

src/main/java/com/dnd/spaced/domain/skill/application/SkillService.java, src/main/java/com/dnd/spaced/domain/skill/presentation/SkillController.java
- closes #126 
Skill 반환 타입 수정
x
x
=> Fix skill return type

src/main/java/com/dnd/spaced/global/security/handler/OAuth2SuccessHandler.java
- closes #131 
oauth 핸들링 방식 변경
자세한건 디스코드 참고
x
x
=> Change oauth handling method

src/main/java/com/dnd/spaced/global/security/handler/OAuth2SuccessHandler.java
- #136 
로그인 이후 리다렉팅 될 url 변경
x
x
=> Fix redirect url after login

src/main/java/com/dnd/spaced/domain/comment/application/dto/CommentServiceMapper.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultipleCommentInfoDto.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/QuerydslCommentRepository.java, src/main/java/com/dnd/spaced/domain/comment/domain/repository/dto/response/CommentInfoWithLikeDto.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultipleCommentInfoResponse.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultiplePopularCommentInfoResponse.java
- closes #140 
- 댓글 목록 조회(용어 상세 페이지 내) 에서 writerInfo response 값 수정
- 반응이 뜨거운 댓글 조회 response 값에서 pronunciationInfo 값 제거
x
x
=> Fix response value

src/main/java/com/dnd/spaced/domain/word/application/WordService.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java, src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/WordControllerMapper.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/SimpleListWordInfoResponse.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/response/SimpleWordInfoResponse.java
- closes #120 
1. 최근의 등록된 용어 api 개발
2. 오늘의 용어 api 개발
x
x
=> Add recent and today's word api

src/main/java/com/dnd/spaced/domain/word/presentation/SwaggerWordController.java
- closes #143 
1. 최근의 등록된 용어 API 문서 추가
2. 오늘의 용어 API 문서 추가
x
x
=> Add recent, today's word api documentation

src/main/java/com/dnd/spaced/global/config/SecurityConfig.java
- closes #133 
cors 관련 세팅 수정
x
x
=> Fix cors configuration source

src/main/java/com/dnd/spaced/domain/admin/domain/repository/QuerydslAdminRepository.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/request/AdminMultipleWordConditionRequest.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java, src/main/java/com/dnd/spaced/domain/quiz/domain/repository/QuerydslQuizRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/presentation/SwaggerWordController.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/MultipleWordConditionRequest.java, src/main/java/com/dnd/spaced/domain/word/presentation/dto/request/WordSearchRequest.java
- closes #146 
카테고리 "전체 실무/전체" -> "전체 실무" 로 통일
x
x
=> Category value unification

src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java, src/main/java/com/dnd/spaced/domain/admin/presentation/dto/response/AdminWordResponse.java
- closes #147 
1. 관리자용 용어 상세 정보 조회 response 출처(resource) 데이터 추가
2. 관리자용 전체 용어 목록 조회 response 출처(resource) 데이터 추가
x
x
=> Add resource data to admin word response

src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java
- closes #149 
관리자 기능에서 카테고리 데이터 '개발', '비즈니스', '디자인' 형태로 수정해서 반환
x
x
=> Admin category response data to korean

src/main/java/com/dnd/spaced/domain/account/domain/CareerInfo.java, src/main/java/com/dnd/spaced/domain/comment/application/dto/response/MultipleCommentInfoDto.java, src/main/java/com/dnd/spaced/domain/comment/presentation/dto/response/MultipleCommentInfoResponse.java
- closes #156 
careerInfo response 데이터 한국어로 변환해서 반환
x
x
=> CareerInfo response data to korean

src/main/java/com/dnd/spaced/domain/word/application/WordService.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java, src/main/java/com/dnd/spaced/domain/word/domain/repository/WordRepository.java, src/main/java/com/dnd/spaced/domain/word/presentation/WordController.java
- closes #155 
전체 용어 개수 조회 API 개발
x
x
=> Add total word count query api

src/main/java/com/dnd/spaced/domain/word/domain/repository/QuerydslWordRepository.java
- closes #161 
용어 상세 페이지 내 댓글 목록 조회 쿼리문 수정
x
x
=> fix :: findWithBookmarkBy querydsl data

src/main/java/com/dnd/spaced/global/security/dto/response/LoginResponse.java, src/main/java/com/dnd/spaced/global/security/handler/OAuth2SuccessHandler.java
- closes #163 
로그인 reponse 값에 권한 정보도 함께 반환되도록 변경
x
이슈 refactor -> fix 변경되어 브랜치 명 refactor 참고
=> Add role value to login response

src/main/java/com/dnd/spaced/global/security/dto/response/LoginResponse.java, src/main/java/com/dnd/spaced/global/security/handler/OAuth2SuccessHandler.java
- closes #168 
로그인 reponse 값에 유저 id 도 함께 반환되도록 변경
x
x
=> Add user id to login response

src/main/java/com/dnd/spaced/domain/bookmark/application/dto/response/BookmarkWordInfoDto.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/response/BookmarkWordDto.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java
- closes #172 
북마크 조회 response 데이터에 commentCount 추가
x
x
=> Add bookmark list response dat

src/main/java/com/dnd/spaced/domain/bookmark/application/BookmarkService.java, src/main/java/com/dnd/spaced/domain/bookmark/application/dto/BookmarkServiceMapper.java, src/main/java/com/dnd/spaced/domain/bookmark/application/dto/request/BookmarkConditionInfoDto.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/QuerydslBookmarkRepository.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/BookmarkRepositoryMapper.java, src/main/java/com/dnd/spaced/domain/bookmark/domain/repository/dto/request/BookmarkConditionDto.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/BookmarkController.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/SwaggerBookmarkController.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/request/BookmarkConditionRequest.java, src/main/java/com/dnd/spaced/domain/bookmark/presentation/dto/response/BookmarkWordResponse.java
- closes #174 
북마크 용어 목록 조회 시 북마크 카테고리 필터 추가 개발
x
x
=> Add category filter to bookmark list

src/main/java/com/dnd/spaced/domain/account/application/dto/response/ReadAccountInfoDto.java, src/main/java/com/dnd/spaced/domain/account/presentation/dto/response/AccountInfoResponse.java
- closes #179 
프로필 조회 API response 값에 email 추가
x
x
=> Add email to profile response

src/main/java/com/dnd/spaced/domain/comment/application/CommentService.java
- closes #182 
본인이 작성한 댓글 수정 api 403 해결
x
x
=> Fix edit comments service logic

src/main/java/com/dnd/spaced/domain/account/domain/Experience.java
- closes #185
경력 enum에 '취준생/인턴' 추가
x
x
=> Add experience enum data

src/main/java/com/dnd/spaced/domain/admin/application/AdminServiceMapper.java, src/main/java/com/dnd/spaced/domain/word/domain/Word.java
- closes #183 
어드민 용어 등록 시 출처 누락 이슈 해결
x
x
=> Fix resource missing error

src/main/java/com/dnd/spaced/domain/auth/presentation/dto/request/CareerInfoRequest.java
closes #188 
경력 부분 500 에러 → allowableValues 수정 
x
x
=> Fix experience allowableValues
